export const dataAvatars = {
    data: [
        {
            userId: 1,
            background: 'dbdbdb',
            topType: 1,
            accessoriesType: 1,
            hairColor: 1,
            facialHairType: 1,
            facialHairColor: 1,
            clotheType: 1,
            eyeType: 1,
            eyebrowType: 1,
            mouthType: 1,
            skinColor: 1,
        },
        {
            userId: 2,
            background: 'dbdbdb',
            topType: 1,
            accessoriesType: 1,
            hairColor: 1,
            facialHairType: 1,
            facialHairColor: 1,
            clotheType: 1,
            eyeType: 1,
            eyebrowType: 1,
            mouthType: 1,
            skinColor: 1,
        },
        {
            userId: 3,
            background: 'dbdbdb',
            topType: 1,
            accessoriesType: 1,
            hairColor: 1,
            facialHairType: 1,
            facialHairColor: 1,
            clotheType: 1,
            eyeType: 1,
            eyebrowType: 1,
            mouthType: 1,
            skinColor: 1,
        },
        {
            userId: 4,
            background: 'dbdbdb',
            topType: 1,
            accessoriesType: 1,
            hairColor: 1,
            facialHairType: 1,
            facialHairColor: 1,
            clotheType: 1,
            eyeType: 1,
            eyebrowType: 1,
            mouthType: 1,
            skinColor: 1,
        }
    ]
}